-- D-CHAL launch coupon
-- Run this file once in the Supabase SQL editor.
-- The coupon can be redeemed only by signed-in users with a verified phone number.
-- It is limited to one redemption per account and per verified phone number,
-- and stops automatically at 10,000 redemptions.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.coupon_campaigns (
  code text primary key,
  benefit_months integer not null check (benefit_months > 0),
  max_redemptions integer not null check (max_redemptions > 0),
  redemption_count integer not null default 0 check (redemption_count >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.coupon_redemptions (
  id bigint generated by default as identity primary key,
  coupon_code text not null references public.coupon_campaigns(code),
  user_id uuid not null references auth.users(id) on delete cascade,
  identity_hash text,
  redeemed_at timestamptz not null default now(),
  benefit_ends_at timestamptz not null,
  unique (coupon_code, user_id)
);

alter table public.coupon_redemptions
add column if not exists identity_hash text;

-- Backfill verified phone identities if this migration is reapplied after launch.
update public.coupon_redemptions as redemption
set identity_hash = encode(
  digest(regexp_replace(auth_user.phone, '\D', '', 'g'), 'sha256'),
  'hex'
)
from auth.users as auth_user
where redemption.user_id = auth_user.id
  and redemption.identity_hash is null
  and auth_user.phone_confirmed_at is not null
  and nullif(regexp_replace(coalesce(auth_user.phone, ''), '\D', '', 'g'), '') is not null;

create unique index if not exists coupon_redemptions_coupon_identity_unique
on public.coupon_redemptions (coupon_code, identity_hash)
where identity_hash is not null;

insert into public.coupon_campaigns (
  code,
  benefit_months,
  max_redemptions,
  is_active
)
values ('D-CHAL', 1, 10000, true)
on conflict (code) do update
set benefit_months = excluded.benefit_months,
    max_redemptions = excluded.max_redemptions,
    is_active = excluded.is_active;

alter table public.coupon_campaigns enable row level security;
alter table public.coupon_redemptions enable row level security;

drop policy if exists "Users can read their own coupon redemption" on public.coupon_redemptions;
create policy "Users can read their own coupon redemption"
on public.coupon_redemptions
for select
to authenticated
using (auth.uid() = user_id);

create or replace function public.redeem_dchal_coupon(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user_id uuid := auth.uid();
  v_phone text;
  v_phone_confirmed boolean := false;
  v_identity_hash text;
  v_campaign public.coupon_campaigns%rowtype;
  v_benefit_ends_at timestamptz;
begin
  if v_user_id is null then
    return jsonb_build_object(
      'ok', false,
      'reason', 'authentication_required',
      'message', '로그인이 필요해요.'
    );
  end if;

  select
    nullif(regexp_replace(coalesce(phone, ''), '\D', '', 'g'), ''),
    phone_confirmed_at is not null
  into v_phone, v_phone_confirmed
  from auth.users
  where id = v_user_id;

  if v_phone is null or not v_phone_confirmed then
    return jsonb_build_object(
      'ok', false,
      'reason', 'phone_verification_required',
      'message', '쿠폰 중복 사용 방지를 위해 휴대폰 본인인증이 필요해요.'
    );
  end if;

  v_identity_hash := encode(digest(v_phone, 'sha256'), 'hex');

  select *
  into v_campaign
  from public.coupon_campaigns
  where code = upper(trim(p_code))
  for update;

  if not found or not v_campaign.is_active then
    return jsonb_build_object(
      'ok', false,
      'reason', 'invalid_coupon',
      'message', '유효하지 않은 쿠폰이에요.'
    );
  end if;

  if exists (
    select 1
    from public.coupon_redemptions
    where coupon_code = v_campaign.code
      and (
        user_id = v_user_id
        or identity_hash = v_identity_hash
      )
  ) then
    return jsonb_build_object(
      'ok', false,
      'reason', 'already_redeemed',
      'message', '이미 이 계정 또는 휴대폰 번호로 사용한 쿠폰이에요.'
    );
  end if;

  if v_campaign.redemption_count >= v_campaign.max_redemptions then
    return jsonb_build_object(
      'ok', false,
      'reason', 'limit_reached',
      'message', '무료 쿠폰 10,000명이 모두 마감됐어요.'
    );
  end if;

  v_benefit_ends_at := now() + make_interval(months => v_campaign.benefit_months);

  insert into public.coupon_redemptions (
    coupon_code,
    user_id,
    identity_hash,
    benefit_ends_at
  )
  values (
    v_campaign.code,
    v_user_id,
    v_identity_hash,
    v_benefit_ends_at
  );

  update public.coupon_campaigns
  set redemption_count = redemption_count + 1
  where code = v_campaign.code;

  return jsonb_build_object(
    'ok', true,
    'coupon_code', v_campaign.code,
    'benefit_months', v_campaign.benefit_months,
    'benefit_ends_at', v_benefit_ends_at,
    'remaining', v_campaign.max_redemptions - v_campaign.redemption_count - 1,
    'message', 'D-CHAL 쿠폰이 적용됐어요.'
  );
exception
  when unique_violation then
    return jsonb_build_object(
      'ok', false,
      'reason', 'already_redeemed',
      'message', '이미 이 계정 또는 휴대폰 번호로 사용한 쿠폰이에요.'
    );
end;
$$;

revoke all on function public.redeem_dchal_coupon(text) from public;
grant execute on function public.redeem_dchal_coupon(text) to authenticated;

-- Restore the signed-in user's active Plus benefit after a refresh or a new visit.
create or replace function public.get_my_dchal_plus_status()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_redemption public.coupon_redemptions%rowtype;
begin
  if v_user_id is null then
    return jsonb_build_object(
      'ok', false,
      'active', false,
      'reason', 'authentication_required'
    );
  end if;

  select *
  into v_redemption
  from public.coupon_redemptions
  where user_id = v_user_id
    and benefit_ends_at > now()
  order by benefit_ends_at desc
  limit 1;

  if not found then
    return jsonb_build_object(
      'ok', true,
      'active', false
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'active', true,
    'coupon_code', v_redemption.coupon_code,
    'benefit_ends_at', v_redemption.benefit_ends_at
  );
end;
$$;

revoke all on function public.get_my_dchal_plus_status() from public;
grant execute on function public.get_my_dchal_plus_status() to authenticated;
